# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ostukiwanie rzeczywistości
author: Maciej Satkiewicz
email: msatkiewicz@gmail.com
description: Personal blog of Maciej Satkiewicz
url: "https://satkiewicz.it" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

hero_img: 'panteon.jpg'
img_url: '/assets/img/'

lang: pl

social:
  links:
    - https://www.facebook.com/maciej.satkiewicz
    - https://www.linkedin.com/in/maciej-satkiewicz-224677a6/
    - https://plus.google.com/u/0/112829985071511370050
    - https://github.com/Swarzkopf314

github_username:  Swarzkopf314
facebook_username: maciej.satkiewicz
linkedin_username: maciej-satkiewicz-224677a6/
youtube_username: UC2T-DFgVhqdz5hv1-Nadv6g
google_analytics: UA-125781990-1

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

disqus:
  shortname: satkiewicz-it

paginate: 9

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

collections_dir: collections
# permalink: /:collection/:title/

collections:
  poems:
    output: true
    permalink: blog/:collection/:title/
    # lang: "default"
  posts:
    output: true
    permalink: blog/:collection/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "poems"
    values:
      layout: poem

sass:
  sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
